<a href="https://colab.research.google.com/github/nirmalya8/PyTorchBasics/blob/main/Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch

# Tensor

A tensor is simply a mathematical object that can be used to describe physical properties, just like scalars and vectors. All operations in PyTorch are done using tensors and they can be considered to be the building blocks.

In [15]:
#Using a number
t = torch.tensor(4.)
t , t.dtype,t.shape

(tensor(4.), torch.float32, torch.Size([]))

In [16]:
#Using a list
t1 = torch.tensor([4.,5,6,7,8])
t1,t1.dtype,t1.shape

(tensor([4., 5., 6., 7., 8.]), torch.float32, torch.Size([5]))

Important Observation: All the data in a tensor must be of the same type and if it is not, they are automatically converted to the same data type.

In [17]:
#Using a matrix of numbers
t2 = torch.tensor([[1,2,3.],[4.,5,6],[7,8.,9]])
t2,t2.dtype,t2.shape 

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.float32, torch.Size([3, 3]))

In [18]:
#Using a 3-D Array
t3 = torch.tensor([[[1, 2, 3], 
     [4, 5, 6]], 
    [[7, 8, 9], 
     [10, 11, 12.]]])
t3,t3.dtype,t3.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]]]), torch.float32, torch.Size([2, 2, 3]))

We have to note that we can't create a tensor with irregular size. The shape of the tensor has to be uniform throughout. Let's study a simple example of this case here:

In [19]:
t4 = torch.tensor([[4.,5],[6,7.],[8,9,10.]])
t4,t4.dtype,t4.shape

ValueError: ignored

As expected, an error was shown. 

Tensor Manipulation

In [21]:
#Fill the whole tensor of a certain shape with one number
t5 = torch.full((3,3),8)
t5

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])

In [23]:
#Concatenating two tensors
t6 = torch.cat((t2,t5))
t6,t6.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.],
         [8., 8., 8.],
         [8., 8., 8.],
         [8., 8., 8.]]), torch.Size([6, 3]))

In [24]:
#Using the reshape function
t7 = t3.reshape(3,2,2)
t7

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

Similarly, element wise operations can also be performed like `torch.sin(tensor)` etc

# Gradients From Tensors

One of the main advantages of PyTorch is that we can compute the gradients automatically using a parameter of torch.tensor() called `requires_grads`. The tensors whose `requires_grads` is set to true can have their gradients computed by using `our_function.backward()` and then the value of `tensor.grad` will give the derivative of the function with respect to the tensor.


---

So, the step by step process will be: 
1. Create the required tensors
2. Define the custom function from which the derivatives are to be computed.
3. Compute the derivatives using `backward()`
4. Finally, get the required derivativatives from the value of `tensor.grad`






---

Say, we want to define a function `y = w*x + b`. In this function, we will need a tensor for x,w and b which after computation will output a tensor y. Now, we would want to compute the derivatives with respect to w and b as, in Machine Learning, the weights and the biases are updated till an optimum is reached.So, the `requires_grads` parameter for w and b will be set to true. 

In [25]:
#Step 1: Creating the tensors
x = torch.tensor(5.)
w = torch.tensor(20.,requires_grad=True)
b = torch.tensor(30. , requires_grad=True)
x,w,b

(tensor(5.), tensor(20., requires_grad=True), tensor(30., requires_grad=True))

In [26]:
#Step 2: Defining the function
y = w*x +b
y

tensor(130., grad_fn=<AddBackward0>)

In [27]:
#Step 3: Gradient Computation
y.backward()

In [28]:
#Step 4: Getting the gradients
print("dy/dw = {}".format(w.grad))
print("dy/db = {}".format(b.grad))
#As requires_grad for x is False by default, if we try to get dy/dx, we will get None as the outcome
print("dy/dx = {}".format(x.grad))

dy/dw = 5.0
dy/db = 1.0
dy/dx = None


# Interoperability with numpy

In [29]:
import numpy as np

In [30]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
x,x.shape

(array([[1., 2., 3.],
        [4., 5., 6.]]), (2, 3))

In [32]:
#Converting a numpy array to a torch tensor
t1np = torch.from_numpy(x)
t1np 

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [34]:
#Converting a torch tensor to a numpy array
npa = t1np.numpy()
npa

array([[1., 2., 3.],
       [4., 5., 6.]])